project:
  type: website
  output-dir: docs

website:
  title: "Daniel Verdugo"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/verdugo-danieML
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



